export const DEBT_PAID_CATEGORY_NAME = 'Dívida paga';
export const RECEIVABLE_RECEIVED_CATEGORY_NAME = 'Receita recebida';
export const INCOME_RECEIVED_CATEGORY_NAME = 'Renda';
export const SUBSCRIPTION_CATEGORY_NAME = 'Assinatura';
export const PERSON_SETTLEMENT_CATEGORY_NAME = 'Acerto com pessoa';

export const SYSTEM_CATEGORY_NAMES = [
  DEBT_PAID_CATEGORY_NAME,
  RECEIVABLE_RECEIVED_CATEGORY_NAME,
  INCOME_RECEIVED_CATEGORY_NAME,
  SUBSCRIPTION_CATEGORY_NAME,
  PERSON_SETTLEMENT_CATEGORY_NAME,
];

export const SYSTEM_CATEGORY_ICON = 'Lock';

export const DEBT_PAID_CATEGORY_COLOR = '#65a30d';
export const RECEIVABLE_RECEIVED_CATEGORY_COLOR = '#22c55e';
export const INCOME_RECEIVED_CATEGORY_COLOR = '#3b82f6';
export const SUBSCRIPTION_CATEGORY_COLOR = '#8b5cf6';
export const PERSON_SETTLEMENT_CATEGORY_COLOR = '#64748b';
